### ISSUE TITLE
Diffing project, need master.key

### ISSUE THREAD

**Issue by leehericks** [bensheldon/good_job_rails7#1]
@bensheldon Indeed your project runs on my machine, so I'm going through the diffs.

You don't have a good_job.rb initializer so I'm adding in my initializer, but I don't have your `master.key` to decrypt the credentials.yml.enc.

Since this is a test project, could you add the `master.key` file here or add it to git and push it up?

**Comment by bensheldon** [comment]
@leehericks 👍   just pushed that up in 281c3c9
